name: Publish New Version
on:
    push:
      branches: [ master ]

jobs:
  PublishNewVersion:
    name: Publish New Version
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
      - run: npm i && npm run build && echo "//npm.pkg.github.com/:_authToken=${{ secrets.GITHUB_TOKEN }}" > ~/.npmrc && npm publish